<?php

use Illuminate\Database\Seeder;

class RecipesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return vo'id'
     */
    public function run()
    {
        \DB::table('recipes')->truncate();
        \DB::table('recipes')->insert(
        [
            0 => [
                'id'=> 1,
                'created_at'=> "2015-06-30 17:58:00",
                'updated_at'=> "2015-06-30 17:58:00",
                'box_type'=> "vegetarian",
                'title'=> "Sweet Chilli and Lime Beef on a Crunchy Fresh",
                'slug'=> "sweet-chilli-and-lime-beef-on-a-crunchy-fresh",
                'short_title'=> "",
                'marketing_description'=> "Here we've used onglet steak which is an extra flavoursome cut of beef that should never be cooked past medium rare. So if you're a fan of well done steak, this one may not be for you. However, if you love rare steak and fancy trying a new cut, please be",
                'calories_kcal'=> 401,
                'protein_grams'=> 12,
                'fat_grams'=> 35,
                'carbs_grams'=> 0,
                'bulletpoint1'=> "",
                'bulletpoint2'=> "",
                'bulletpoint3'=> "",
                'recipe_diet_type_id'=> "meat",
                'season'=> "all",
                'base'=> "noodles",
                'protein_source'=> "beef",
                'preparation_time_minutes'=> 35,
                'shelf_life_days'=> 4,
                'equipment_needed'=> "Appetite",
                'origin_country'=> "Great Britain",
                'recipe_cuisine'=> "asian",
                'in_your_box'=> "",
                'gousto_reference'=> 59
            ],
                1 =>[
                'id'=> 2,
                'created_at'=> "2015-06-30 17:58:00",
                'updated_at'=> "2015-06-30 17:58:00",
                'box_type'=> "gourmet",
                'title'=> "Tamil Nadu Prawn Masala",
                'slug'=> "tamil-nadu-prawn-masala",
                'short_title'=> "",
                'marketing_description'=> "Tamil Nadu is a state on the eastern coast of the southern tip of India. Curry from there is particularly famous and it's easy to see why. This one is brimming with exciting contrasting tastes from ingredients like chilli powder, coriander and fennel seed",
                'calories_kcal'=> 524,
                'protein_grams'=> 12,
                'fat_grams'=> 22,
                'carbs_grams'=> 0,
                'bulletpoint1'=> "Vibrant & Fresh",
                'bulletpoint2'=> "Warming, not spicy",
                'bulletpoint3'=> "Curry From Scratch",
                'recipe_diet_type_id'=> "fish",
                'season'=> "all",
                'base'=> "pasta",
                'protein_source'=> "seafood",
                'preparation_time_minutes'=> 40,
                'shelf_life_days'=> 4,
                'equipment_needed'=> "Appetite",
                'origin_country'=> "Great Britain",
                'recipe_cuisine'=> "italian",
                'in_your_box'=> "king prawns, basmati rice, onion, tomatoes, garlic, ginger, ground tumeric, red chilli powder, ground cumin, fresh coriander, cu",
                'gousto_reference'=> 58
            ],
        2 =>[
                'id'=> 3,
                'created_at'=> "2015-06-30 17:58:00",
                'updated_at'=> "2015-06-30 17:58:00",
                'box_type'=> "vegetarian",
                'title'=> "Umbrian Wild Boar Salami Ragu with Linguine",
                'slug'=> "umbrian-wild-boar-salami-ragu-with-linguine",
                'short_title'=> "",
                'marketing_description'=> "This delicious pasta dish comes from the Italian region of Umbria. It has a smoky and intense wild boar flavour which combines the earthy garlic, leek and onion flavours, while the chilli flakes add a nice deep aroma. Enjoy within 5-6 days of delivery.",
                'calories_kcal'=> 609,
                'protein_grams'=> 17,
                'fat_grams'=> 29,
                'carbs_grams'=> 0,
                'bulletpoint1'=> "",
                'bulletpoint2'=> "",
                'bulletpoint3'=> "",
                'recipe_diet_type_id'=> "meat",
                'season'=> "all",
                'base'=> "pasta",
                'protein_source'=> "pork",
                'preparation_time_minutes'=> 35,
                'shelf_life_days'=> 4,
                'equipment_needed'=> "Appetite",
                'origin_country'=> "Great Britain",
                'recipe_cuisine'=> "british",
                'in_your_box'=> "",
                'gousto_reference'=> 1
            ],
        3 =>[
                'id'=> 4,
                'created_at'=> "2015-06-30 17:58:00",
                'updated_at'=> "2015-06-30 17:58:00",
                'box_type'=> "gourmet",
                'title'=> "Tenderstem and Portobello Mushrooms with Corn",
                'slug'=> "tenderstem-and-portobello-mushrooms-with-corn",
                'short_title'=> "",
                'marketing_description'=> "One for those who like their veggies with a slightly spicy kick. However, those short on time, be warned ' this is a time-consuming dish, but if you're willing to spend a few extra minutes in the kitchen, the fresh corn mash is extraordinary and worth a t",
                'calories_kcal'=> 508,
                'protein_grams'=> 28,
                'fat_grams'=> 20,
                'carbs_grams'=> 0,
                'bulletpoint1'=> "",
                'bulletpoint2'=> "",
                'bulletpoint3'=> "",
                'recipe_diet_type_id'=> "vegetarian",
                'season'=> "all",
                'base'=> "",
                'protein_source'=> "cheese",
                'preparation_time_minutes'=> 50,
                'shelf_life_days'=> 4,
                'equipment_needed'=> "None",
                'origin_country'=> "Great Britain",
                'recipe_cuisine'=> "british",
                'in_your_box'=> "",
                'gousto_reference'=> 56
            ],
        4 =>[
                'id'=> 5,
                'created_at'=> "2015-06-30 17:58:00",
                'updated_at'=> "2015-06-30 17:58:00",
                'box_type'=> "vegetarian",
                'title'=> "Fennel Crusted Pork with Italian Butter Beans",
                'slug'=> "fennel-crusted-pork-with-italian-butter-beans",
                'short_title'=> "",
                'marketing_description'=> "A classic roast with a twist. The pork loin is marinated in rosemary, fennel seeds and chilli flakes then teamed with baked potato wedges and butter beans in tomato sauce. Enjoy within 5-6 days of delivery.",
                'calories_kcal'=> 511,
                'protein_grams'=> 11,
                'fat_grams'=> 62,
                'carbs_grams'=> 0,
                'bulletpoint1'=> "A roast with a twist",
                'bulletpoint2'=> "Low fat & high protein",
                'bulletpoint3'=> "With roast potatoes",
                'recipe_diet_type_id'=> "meat",
                'season'=> "all",
                'base'=> "beans/lentils",
                'protein_source'=> "pork",
                'preparation_time_minutes'=> 45,
                'shelf_life_days'=> 4,
                'equipment_needed'=> "Pestle & Mortar (optional)",
                'origin_country'=> "Great Britain",
                'recipe_cuisine'=> "british",
                'in_your_box'=> "pork tenderloin, potatoes, butter beans, garlic, fennel seeds, medium onion, chilli flakes, fresh rosemary, tomatoes, vegetable ",
                'gousto_reference'=> 55
            ],
        5 =>[
                'id'=> 6,
                'created_at'=> "2015-07-01 17:58:00",
                'updated_at'=> "2015-07-01 17:58:00",
                'box_type'=> "gourmet",
                'title'=> "Pork Chilli",
                'slug'=> "pork-chilli",
                'short_title'=> "",
                'marketing_description'=> "Succulent pork tenderloin and feathery white bean and parsnip mash mingle with feisty cumin seeds and tangy leek in this lighter, less conventional take on a British classic. Welcome to the outer limits of food!",
                'calories_kcal'=> 401,
                'protein_grams'=> 12,
                'fat_grams'=> 35,
                'carbs_grams'=> 0,
                'bulletpoint1'=> "",
                'bulletpoint2'=> "",
                'bulletpoint3'=> "",
                'recipe_diet_type_id'=> "meat",
                'season'=> "all",
                'base'=> "",
                'protein_source'=> "pork",
                'preparation_time_minutes'=> 35,
                'shelf_life_days'=> 4,
                'equipment_needed'=> "Appetite",
                'origin_country'=> "Great Britain",
                'recipe_cuisine'=> "asian",
                'in_your_box'=> "",
                'gousto_reference'=> 60
            ],
        6 =>[
                'id'=> 7,
                'created_at'=> "2015-07-02 17:58:00",
                'updated_at'=> "2015-07-02 17:58:00",
                'box_type'=> "vegetarian",
                'title'=> "Courgette Pasta Rags",
                'slug'=> "courgette-pasta-rags",
                'short_title'=> "",
                'marketing_description'=> "Kick-start the new year with some get-up and go with this lean green vitality machine. Protein-packed chicken and mineral-rich kale are blended into a smooth, nut-free version of pesto; creating the ultimate composition of nutrition and taste",
                'calories_kcal'=> 524,
                'protein_grams'=> 12,
                'fat_grams'=> 22,
                'carbs_grams'=> 0,
                'bulletpoint1'=> "",
                'bulletpoint2'=> "",
                'bulletpoint3'=> "",
                'recipe_diet_type_id'=> "meat",
                'season'=> "all",
                'base'=> "",
                'protein_source'=> "chicken",
                'preparation_time_minutes'=> 40,
                'shelf_life_days'=> 4,
                'equipment_needed'=> "Appetite",
                'origin_country'=> "Great Britain",
                'recipe_cuisine'=> "british",
                'in_your_box'=> "",
                'gousto_reference'=> 59
            ],
        7 =>[
                'id'=> 8,
                'created_at'=> "2015-07-03 17:58:00",
                'updated_at'=> "2015-07-03 17:58:00",
                'box_type'=> "vegetarian",
                'title'=> "Homemade Eggs & Beans",
                'slug'=> "homemade-egg-beans",
                'short_title'=> "",
                'marketing_description'=> "A Goustofied British institution, learn how to make beautifully golden breaded chicken escalopes drizzled in homemade garlic butter and served atop fluffy potato and broccoli mash.",
                'calories_kcal'=> 609,
                'protein_grams'=> 17,
                'fat_grams'=> 29,
                'carbs_grams'=> 0,
                'bulletpoint1'=> "",
                'bulletpoint2'=> "",
                'bulletpoint3'=> "",
                'recipe_diet_type_id'=> "meat",
                'season'=> "all",
                'base'=> "",
                'protein_source'=> "eggs",
                'preparation_time_minutes'=> 35,
                'shelf_life_days'=> 3,
                'equipment_needed'=> "Appetite",
                'origin_country'=> "Great Britain",
                'recipe_cuisine'=> "italian",
                'in_your_box'=> "",
                'gousto_reference'=> 2
            ],
        8 =>[
                'id'=> 9,
                'created_at'=> "2015-07-04 17:58:00",
                'updated_at'=> "2015-07-04 17:58:00",
                'box_type'=> "gourmet",
                'title'=> "Grilled Jerusalem Fish",
                'slug'=> "grilled-jerusalem-fish",
                'short_title'=> "",
                'marketing_description'=> "I love this super healthy fish dish, it contains a punch from zingy ginger, a kick from chili and a salty sweet balance from soy sauce and mirim. A cleansing and restorative meal, great for body and soul.",
                'calories_kcal'=> 508,
                'protein_grams'=> 28,
                'fat_grams'=> 20,
                'carbs_grams'=> 0,
                'bulletpoint1'=> "",
                'bulletpoint2'=> "",
                'bulletpoint3'=> "",
                'recipe_diet_type_id'=> "meat",
                'season'=> "all",
                'base'=> "",
                'protein_source'=> "fish",
                'preparation_time_minutes'=> 50,
                'shelf_life_days'=> 4,
                'equipment_needed'=> "Appetite",
                'origin_country'=> "Great Britain",
                'recipe_cuisine'=> "mediterranean",
                'in_your_box'=> "",
                'gousto_reference'=> 57
            ],
        9 =>[
                'id'=> 10,
                'created_at'=> "2015-07-05 17:58:00",
                'updated_at'=> "2015-07-05 17:58:00",
                'box_type'=> "gourmet",
                'title'=> "Pork Katsu Curry",
                'slug'=> "pork-katsu-curry",
                'short_title'=> "",
                'marketing_description'=> "Comprising all the best bits of the classic American number and none of the mayo, this is a warm & tasty chicken and bulgur salad with just a hint of Scandi influence. A beautifully summery medley of flavours and textures",
                'calories_kcal'=> 511,
                'protein_grams'=> 11,
                'fat_grams'=> 62,
                'carbs_grams'=> 0,
                'bulletpoint1'=> "",
                'bulletpoint2'=> "",
                'bulletpoint3'=> "",
                'recipe_diet_type_id'=> "meat",
                'season'=> "all",
                'base'=> "",
                'protein_source'=> "pork",
                'preparation_time_minutes'=> 45,
                'shelf_life_days'=> 4,
                'equipment_needed'=> "Appetite",
                'origin_country'=> "Great Britain",
                'recipe_cuisine'=> "mexican",
                'in_your_box'=> "",
                'gousto_reference'=> 56
            ],
        10 =>[
                'id'=> 11,
                'created_at'=> "2017-07-20 11:36:01",
                'updated_at'=> "2017-07-20 12:00:16",
                'box_type'=> "vegetarian",
                'title'=> "Pesto penne pasta with olive oil",
                'slug'=> "pesto-penne-pasta-with-olive-oil",
                'short_title'=> "Penne Pesto",
                'marketing_description'=> "1	In a pan, roast together pomegranate and cumin seeds and grind to a powder.
        2	Put water, chickpeas, 4 tsp salt, cardamoms, cinnamon and cloves in cooker. Stir.
        3	Close cooker. Bring to full pressure on high heat. Reduce heat and cook for 18 minutes.
        4	Remove cooker from heat. Allow to cool naturally.
        5	Open cooker. Drain off cooking liqu'id' and reserve. Add remaining salt ( 3 ½ tsp), pomegranate-cumin, coriander, pepper, garam masala and mango powders. Mix till chickpeas are coated with spices. Sprinkle chillies and ginger on top.
        6	In a pan, heat oil and ghee till smoky ( approximately 5 minutes) and pour evenly over chickpeas. Add cooking liqu'id'.
        7	Place cooker on medium heat. Cook till liqu'id' dries up and oil shows seperately (approximately 10 minutes), stirring occasionally.
        8	Place chickpeas on serving dish. Serve hot, granished with onion and lemon wedges.",
                'calories_kcal'=> 500,
                'protein_grams'=> 15,
                'fat_grams'=> 10,
                'carbs_grams'=> 20,
                'bulletpoint1'=> "pasta",
                'bulletpoint2'=> "penne",
                'bulletpoint3'=> "pesto",
                'recipe_diet_type_id'=> "vegetarian",
                'season'=> "all",
                'base'=> "pasta",
                'protein_source'=> "bean",
                'preparation_time_minutes'=> 30,
                'shelf_life_days'=> 5,
                'equipment_needed'=> "Appetite",
                'origin_country'=> "Britain",
                'recipe_cuisine'=> "british",
                'in_your_box'=> null,
                'gousto_reference'=> 100
            ]
        ]);
    }
}





